/******************************************************************************/ 
/*! 
\file   M5StageTypes.h 
\author UserPreBuild.bat 
\par    email: lazersquad\@gmail.com 
\par    Mach5 Game Engine 
 
This file gets auto generated based on the names of the Stages in the 
current project.  UserPreBuild.bat looks for files of the type *Stage.h 
and creates an enumeration value of ST_*Stage. 
*/ 
/******************************************************************************/ 
#ifndef M5STAGE_TYPES_H 
#define M5STAGE_TYPES_H 
 
 
//! AutoGenerated enum based on stage file names  
enum M5StageTypes {  
ST_GamePlayStage, 
ST_PauseStage, 
ST_SplashStage, 
ST_INVALID 
}; 
#endif //M5STAGE_TYPES_H 
