/******************************************************************************/ 
/*! 
\file   M5ComponentTypes.h 
\author UserPreBuild.bat 
\par    email: lazersquad\@gmail.com 
\par    Mach5 Game Engine 
 
This file gets auto generated based on the names of the Components in the 
current project.  UserPreBuild.bat looks for files of the type *Component.h 
and creates an enumeration value of CT_*Component. 
*/ 
/******************************************************************************/ 
#ifndef M5COMPONENT_TYPE_H 
#define M5COMPONENT_TYPE_H 
#include <string> 
 
 
//! AutoGenerated enum based on component file names  
enum M5ComponentTypes {  
CT_ClampComponent, 
CT_GfxComponent, 
CT_OutsideViewKillComponent, 
CT_WrapComponent, 
CT_ChasePlayerComponent, 
CT_PlayerInputComponent, 
CT_RandomGoComponent, 
CT_ShrinkComponent, 
CT_INVALID 
}; 
 
 
//! AutoGenerated function to convert strings to our M5ComponentTypes type 
inline M5ComponentTypes StringToComponent(const std::string& string) { 
if(string == "ClampComponent") return CT_ClampComponent; 
if(string == "GfxComponent") return CT_GfxComponent; 
if(string == "OutsideViewKillComponent") return CT_OutsideViewKillComponent; 
if(string == "WrapComponent") return CT_WrapComponent; 
if(string == "ChasePlayerComponent") return CT_ChasePlayerComponent; 
if(string == "PlayerInputComponent") return CT_PlayerInputComponent; 
if(string == "RandomGoComponent") return CT_RandomGoComponent; 
if(string == "ShrinkComponent") return CT_ShrinkComponent; 
return CT_INVALID; 
} 
#endif //M5COMPONENT_TYPE_H 
